insert into roles (id, role) values (1, "Commander");
insert into roles (id, role) values (2, "Vice Commander");
insert into roles (id, role) values (3, "Deputy Commander");
insert into roles (id, role) values (4, "Command Chief");
insert into roles (id, role) values (5, "Section Chief");
insert into roles (id, role) values (6, "Flight Chief");
insert into roles (id, role) values (7, "First Sergeant");
insert into roles (id, role) values (8, "Chief Enlisted Manager");
insert into roles (id, role) values (9, "Senior Enlisted Manager");
insert into roles (id, role) values (10, "NCOIC");
